rain:
  duration: 30  # длительность кислотного дождя в секундах
  startMessage: "<yellow>⚠ Начался кислотный дождь! Длительность: %duration% секунд."
  endMessage: "<green>☀ Кислотный дождь закончился."

lightning:
  duration: 30  # длительность шторма молний в секундах
  intensity: 5  # количество молний за секунду
  radius: 30  # радиус для удара молнии в блоках
  startMessage: "<yellow>⚡ Начался шторм молний! Длительность: %duration% секунд."
  endMessage: "<gray>🌩 Шторм молний завершен."

revenge:
  duration: 60  # длительность события в секундах
  startMessage: "<green>Месть мирных животных активирована на <yellow>%duration% <green>секунд."
  alreadyActiveMessage: "<red>Месть мирных животных уже активирована!"
  endMessage: "<red>Месть мирных животных отключена."
